name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            bash -l -c '
              cd ~/auth-api-default &&
              git pull origin master &&
              npm install &&
              npm run migrate up &&
              pm2 restart auth-api-default || pm2 start src/app.js --name auth-api-default
